(cl:defpackage corbslam_server-srv
  (:use )
  (:export
   "CORBSLAM_INSERT"
   "<CORBSLAM_INSERT-REQUEST>"
   "CORBSLAM_INSERT-REQUEST"
   "<CORBSLAM_INSERT-RESPONSE>"
   "CORBSLAM_INSERT-RESPONSE"
   "CORBSLAM_UPDATE"
   "<CORBSLAM_UPDATE-REQUEST>"
   "CORBSLAM_UPDATE-REQUEST"
   "<CORBSLAM_UPDATE-RESPONSE>"
   "CORBSLAM_UPDATE-RESPONSE"
  ))

