(cl:defpackage corbslam_client-srv
  (:use )
  (:export
   "CORBSLAM_INSERT"
   "<CORBSLAM_INSERT-REQUEST>"
   "CORBSLAM_INSERT-REQUEST"
   "<CORBSLAM_INSERT-RESPONSE>"
   "CORBSLAM_INSERT-RESPONSE"
   "CORBSLAM_UPDATE"
   "<CORBSLAM_UPDATE-REQUEST>"
   "CORBSLAM_UPDATE-REQUEST"
   "<CORBSLAM_UPDATE-RESPONSE>"
   "CORBSLAM_UPDATE-RESPONSE"
   "ORBSLAM_CLIENT_TESTSRV"
   "<ORBSLAM_CLIENT_TESTSRV-REQUEST>"
   "ORBSLAM_CLIENT_TESTSRV-REQUEST"
   "<ORBSLAM_CLIENT_TESTSRV-RESPONSE>"
   "ORBSLAM_CLIENT_TESTSRV-RESPONSE"
  ))

